// <auto-generated />
using Aurora.User.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aurora.User.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Aurora.User.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            EmailId = "User_1@gmail.com",
                            FirstName = "User_1",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 2,
                            EmailId = "User_2@gmail.com",
                            FirstName = "User_2",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 3,
                            EmailId = "User_3@gmail.com",
                            FirstName = "User_3",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 4,
                            EmailId = "User_4@gmail.com",
                            FirstName = "User_4",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 5,
                            EmailId = "User_5@gmail.com",
                            FirstName = "User_5",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 6,
                            EmailId = "User_6@gmail.com",
                            FirstName = "User_6",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 7,
                            EmailId = "User_7@gmail.com",
                            FirstName = "User_7",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 8,
                            EmailId = "User_8@gmail.com",
                            FirstName = "User_8",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 9,
                            EmailId = "User_9@gmail.com",
                            FirstName = "User_9",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 10,
                            EmailId = "User_10@gmail.com",
                            FirstName = "User_10",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 11,
                            EmailId = "User_11@gmail.com",
                            FirstName = "User_11",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 12,
                            EmailId = "User_12@gmail.com",
                            FirstName = "User_12",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 13,
                            EmailId = "User_13@gmail.com",
                            FirstName = "User_13",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 14,
                            EmailId = "User_14@gmail.com",
                            FirstName = "User_14",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 15,
                            EmailId = "User_15@gmail.com",
                            FirstName = "User_15",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 16,
                            EmailId = "User_16@gmail.com",
                            FirstName = "User_16",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 17,
                            EmailId = "User_17@gmail.com",
                            FirstName = "User_17",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 18,
                            EmailId = "User_18@gmail.com",
                            FirstName = "User_18",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 19,
                            EmailId = "User_19@gmail.com",
                            FirstName = "User_19",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 20,
                            EmailId = "User_20@gmail.com",
                            FirstName = "User_20",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 21,
                            EmailId = "User_21@gmail.com",
                            FirstName = "User_21",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 22,
                            EmailId = "User_22@gmail.com",
                            FirstName = "User_22",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 23,
                            EmailId = "User_23@gmail.com",
                            FirstName = "User_23",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 24,
                            EmailId = "User_24@gmail.com",
                            FirstName = "User_24",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 25,
                            EmailId = "User_25@gmail.com",
                            FirstName = "User_25",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 26,
                            EmailId = "User_26@gmail.com",
                            FirstName = "User_26",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 27,
                            EmailId = "User_27@gmail.com",
                            FirstName = "User_27",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 28,
                            EmailId = "User_28@gmail.com",
                            FirstName = "User_28",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 29,
                            EmailId = "User_29@gmail.com",
                            FirstName = "User_29",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 30,
                            EmailId = "User_30@gmail.com",
                            FirstName = "User_30",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 31,
                            EmailId = "User_31@gmail.com",
                            FirstName = "User_31",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 32,
                            EmailId = "User_32@gmail.com",
                            FirstName = "User_32",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 33,
                            EmailId = "User_33@gmail.com",
                            FirstName = "User_33",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 34,
                            EmailId = "User_34@gmail.com",
                            FirstName = "User_34",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 35,
                            EmailId = "User_35@gmail.com",
                            FirstName = "User_35",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 36,
                            EmailId = "User_36@gmail.com",
                            FirstName = "User_36",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 37,
                            EmailId = "User_37@gmail.com",
                            FirstName = "User_37",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 38,
                            EmailId = "User_38@gmail.com",
                            FirstName = "User_38",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 39,
                            EmailId = "User_39@gmail.com",
                            FirstName = "User_39",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 40,
                            EmailId = "User_40@gmail.com",
                            FirstName = "User_40",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 41,
                            EmailId = "User_41@gmail.com",
                            FirstName = "User_41",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 42,
                            EmailId = "User_42@gmail.com",
                            FirstName = "User_42",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 43,
                            EmailId = "User_43@gmail.com",
                            FirstName = "User_43",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 44,
                            EmailId = "User_44@gmail.com",
                            FirstName = "User_44",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 45,
                            EmailId = "User_45@gmail.com",
                            FirstName = "User_45",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 46,
                            EmailId = "User_46@gmail.com",
                            FirstName = "User_46",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 47,
                            EmailId = "User_47@gmail.com",
                            FirstName = "User_47",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 48,
                            EmailId = "User_48@gmail.com",
                            FirstName = "User_48",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 49,
                            EmailId = "User_49@gmail.com",
                            FirstName = "User_49",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 50,
                            EmailId = "User_50@gmail.com",
                            FirstName = "User_50",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 51,
                            EmailId = "User_51@gmail.com",
                            FirstName = "User_51",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 52,
                            EmailId = "User_52@gmail.com",
                            FirstName = "User_52",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 53,
                            EmailId = "User_53@gmail.com",
                            FirstName = "User_53",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 54,
                            EmailId = "User_54@gmail.com",
                            FirstName = "User_54",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 55,
                            EmailId = "User_55@gmail.com",
                            FirstName = "User_55",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 56,
                            EmailId = "User_56@gmail.com",
                            FirstName = "User_56",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 57,
                            EmailId = "User_57@gmail.com",
                            FirstName = "User_57",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 58,
                            EmailId = "User_58@gmail.com",
                            FirstName = "User_58",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 59,
                            EmailId = "User_59@gmail.com",
                            FirstName = "User_59",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 60,
                            EmailId = "User_60@gmail.com",
                            FirstName = "User_60",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 61,
                            EmailId = "User_61@gmail.com",
                            FirstName = "User_61",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 62,
                            EmailId = "User_62@gmail.com",
                            FirstName = "User_62",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 63,
                            EmailId = "User_63@gmail.com",
                            FirstName = "User_63",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 64,
                            EmailId = "User_64@gmail.com",
                            FirstName = "User_64",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 65,
                            EmailId = "User_65@gmail.com",
                            FirstName = "User_65",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 66,
                            EmailId = "User_66@gmail.com",
                            FirstName = "User_66",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 67,
                            EmailId = "User_67@gmail.com",
                            FirstName = "User_67",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 68,
                            EmailId = "User_68@gmail.com",
                            FirstName = "User_68",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 69,
                            EmailId = "User_69@gmail.com",
                            FirstName = "User_69",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 70,
                            EmailId = "User_70@gmail.com",
                            FirstName = "User_70",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 71,
                            EmailId = "User_71@gmail.com",
                            FirstName = "User_71",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 72,
                            EmailId = "User_72@gmail.com",
                            FirstName = "User_72",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 73,
                            EmailId = "User_73@gmail.com",
                            FirstName = "User_73",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 74,
                            EmailId = "User_74@gmail.com",
                            FirstName = "User_74",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 75,
                            EmailId = "User_75@gmail.com",
                            FirstName = "User_75",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 76,
                            EmailId = "User_76@gmail.com",
                            FirstName = "User_76",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 77,
                            EmailId = "User_77@gmail.com",
                            FirstName = "User_77",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 78,
                            EmailId = "User_78@gmail.com",
                            FirstName = "User_78",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 79,
                            EmailId = "User_79@gmail.com",
                            FirstName = "User_79",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 80,
                            EmailId = "User_80@gmail.com",
                            FirstName = "User_80",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 81,
                            EmailId = "User_81@gmail.com",
                            FirstName = "User_81",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 82,
                            EmailId = "User_82@gmail.com",
                            FirstName = "User_82",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 83,
                            EmailId = "User_83@gmail.com",
                            FirstName = "User_83",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 84,
                            EmailId = "User_84@gmail.com",
                            FirstName = "User_84",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 85,
                            EmailId = "User_85@gmail.com",
                            FirstName = "User_85",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 86,
                            EmailId = "User_86@gmail.com",
                            FirstName = "User_86",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 87,
                            EmailId = "User_87@gmail.com",
                            FirstName = "User_87",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 88,
                            EmailId = "User_88@gmail.com",
                            FirstName = "User_88",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 89,
                            EmailId = "User_89@gmail.com",
                            FirstName = "User_89",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 90,
                            EmailId = "User_90@gmail.com",
                            FirstName = "User_90",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 91,
                            EmailId = "User_91@gmail.com",
                            FirstName = "User_91",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 92,
                            EmailId = "User_92@gmail.com",
                            FirstName = "User_92",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 93,
                            EmailId = "User_93@gmail.com",
                            FirstName = "User_93",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 94,
                            EmailId = "User_94@gmail.com",
                            FirstName = "User_94",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 95,
                            EmailId = "User_95@gmail.com",
                            FirstName = "User_95",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 96,
                            EmailId = "User_96@gmail.com",
                            FirstName = "User_96",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 97,
                            EmailId = "User_97@gmail.com",
                            FirstName = "User_97",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 98,
                            EmailId = "User_98@gmail.com",
                            FirstName = "User_98",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 99,
                            EmailId = "User_99@gmail.com",
                            FirstName = "User_99",
                            LastName = "Aurora"
                        },
                        new
                        {
                            UserId = 100,
                            EmailId = "User_100@gmail.com",
                            FirstName = "User_100",
                            LastName = "Aurora"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
